#1
# NOTE: TO COMPOSE TYPE "docker compose --env-file=.env.*** up --build"
#
# CHANGE " *** " AND CHOOSE BETWEEN "dev" / "test" / "prod"
#

services:
    PGSQL:
        image: postgres:${POSTGRES_VERSION}
        container_name: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
    Redis:
        image: redis:${REDIS_VERSION}
        container_name: redis
        ports:
            - ${REDIS_VERSION}:6378
    auth:
        build:
            context: ./Auth
            dockerfile: Dockerfile
        container_name: auth_service
        ports:
            - ${AUTH_PORT}:8000
    board:
        build:
            context: ./Board_Service
            dockerfile: Dockerfile
        container_name: board_service
        ports:
            - ${BOARD_PORT}:8000
networks:
    app-network:
        driver: bridge
