#1
# NOTE: TO COMPOSE TYPE "docker compose --env-file=.env.*** up --build"
#
# CHANGE " *** " AND CHOOSE BETWEEN "dev" / "test" / "prod"
#

services:
    PGSQL:
        image: postgres:${POSTGRES_VERSION}
        container_name: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
    Redis:
        image: redis:${REDIS_VERSION}
        container_name: redis
        ports:
            - ${REDIS_VERSION}:6378
    board_service:
        build: ./Board_Service
        container_name: board_service
        ports:
            - "8000:8000"
        environment:
            - PYTHONUNBUFFERED=1
        # Для разработки с hot-reload:
        command: uvicorn board_service.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./:/app
        restart: unless-stopped
        networks:
            - app-network
    Auth:
        build:
            context: ./Auth
            dockerfile: Dockerfile
        container_name: auth_service
        ports:
            - "${AUTH_PORT:-8001}:8000"
networks:
    app-network:
        driver: bridge
