version: '3.8'

services:
    PGSQL:
        image: PostgreSQL:17
        container_name: PostgreSQL
        environment:
            - PG_USER=user
            - PG_PASSWORD=${PGSQL_PASSWORD}
            - PG_DB=user
        ports:
            - 5432:5432
    Redis:
        image: Redis:8
        container_name: redis
        ports:
            -"6378:6379"
        
